# Pipeline Configuration
pipeline:
  fetch_interval_hours: 1
  processing_batch_size: 100
  max_concurrent_scrapes: 5
  time_window_hours: 168  # 7 days instead of 72 hours
  
# Cybersecurity Filter Keywords (Fallback - primary filtering uses security_keywords.yaml)
security_keywords:
  - cybersecurity
  - malware
  - ransomware
  - phishing
  - breach
  - vulnerability
  - exploit
  - attack
  - threat
  - hacker
  - security
  - CVE
  - zero-day
  - APT
  - botnet

# Semantic Clustering
clustering:
  model_name: "sentence-transformers/all-mpnet-base-v2"
  similarity_threshold: 0.70  # Lowered from 0.75 for better evolving story detection
  min_cluster_size: 2
  max_cluster_size: 25  # Increased from 12 to handle larger ongoing stories
  time_window_hours: 168  # Increased from 168 (1 week) to 336 (2 weeks)
  coherence_threshold: 0.70
  batch_size: 50

# Entity Extraction
entities:
  regex_patterns:
    cve: 'CVE-\d{4}-\d{4,}'
    file_hash_md5: '[a-fA-F0-9]{32}'
    file_hash_sha1: '[a-fA-F0-9]{40}'
    file_hash_sha256: '[a-fA-F0-9]{64}'
    ip_address: '\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b'
    domain: '[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9]?\.[a-zA-Z]{2,}'
  
  dynamic_weights:
    cve: 80
    file_hash: 60
    ip_address: 55
    domain: 50

# Ranking Algorithm
ranking:
  weights:
    recency: 0.20
    source_credibility: 0.30
    entity_importance: 0.30
    keyword_severity: 0.20
  
  recency_decay_hours: 24

# Web Scraping
scraping:
  timeout_seconds: 30
  max_retries: 3
  rate_limit_delay: 1.0
  user_agent: "ThreatCluster/1.0 (+https://threatcluster.io/helper)"

# Monitoring
monitoring:
  health_check_port: 8080
  metrics_retention_days: 30

# Scheduler Configuration
scheduler:
  enabled: true
  components:
    rss_fetcher:
      enabled: true
      interval_minutes: 60
      description: "Fetch RSS feeds from configured sources"
    article_scraper:
      enabled: true
      interval_minutes: 30
      delay_after_fetch_minutes: 5
      description: "Scrape full article content from URLs"
    entity_extractor:
      enabled: true
      interval_minutes: 45
      description: "Extract entities from article content"
    semantic_clusterer:
      enabled: true
      interval_minutes: 120
      description: "Group related articles into clusters"
    article_ranker:
      enabled: true
      interval_minutes: 60
      description: "Calculate article and cluster rankings"
    ioc_fetcher:
      enabled: true
      interval_minutes: 1440  # 24 hours
      description: "Fetch IOCs from threat intelligence feeds"
    ai_summary:
      enabled: true
      interval_minutes: 60
      batch_size: 10
      description: "Generate AI-powered summaries for clusters"

# AI Summary Configuration
ai_summary:
  model: "gpt-4o-mini"
  max_articles_per_cluster: 10
  max_chars_per_article: 500
  temperature: 0.3
  max_retries: 3
  retry_delay_seconds: 2