# Enhanced Security Keywords Configuration with Scoring
# Used for filtering articles to ensure security relevance

# Scoring thresholds by feed category
scoring_thresholds:
  cybersecurity: 30      # Dedicated security feeds - lower threshold
  general_news: 70       # General tech news - higher threshold required
  minimum_score: 25      # Absolute minimum for any feed

# Positive scoring signals
positive_signals:
  # Security keywords with weight by severity
  critical_keywords:  # Score: 30
    - "zero-day"
    - "0-day"
    - "critical vulnerability"
    - "rce"
    - "remote code execution"
    - "ransomware attack"
    - "data breach"
    - "security breach"
    - "cyber attack"
    - "cyberattack"
    
  high_keywords:  # Score: 20
    - "vulnerability"
    - "exploit"
    - "breach"
    - "ransomware"
    - "malware"
    - "trojan"
    - "backdoor"
    - "apt"
    - "advanced persistent threat"
    - "compromise"
    - "hacked"
    - "incident"
    - "phishing attack"
    - "phishing campaign"
    - "phishing"
    - "ddos"
    - "denial of service"
    - "attack"
    - "threat actor"
    - "security flaw"
    - "security issue"
    - "malware analysis"
    - "threat intelligence"
    - "forensics"
    - "security"
    - "cybersecurity"
    - "infosec"
    - "threat"
    - "risk"
    - "patch"
    - "update"
    - "advisory"
    
  # Action verbs that indicate security events (bonus points)
  action_verbs:  # Score: +15 when near security keyword
    - "discovered"
    - "found"
    - "detected"
    - "exploited"
    - "breached"
    - "compromised"
    - "patched"
    - "fixed"
    - "mitigated"
    - "disclosed"
    - "reported"
    - "identified"
    
  # Technical indicators (regex patterns with scores)
  technical_indicators:
    cve_pattern: 
      pattern: 'CVE-\d{4}-\d{4,}'
      score: 25
    ip_address:
      pattern: '\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b'
      score: 15
    md5_hash:
      pattern: '\b[a-fA-F0-9]{32}\b'
      score: 20
    sha256_hash:
      pattern: '\b[a-fA-F0-9]{64}\b'
      score: 20
      
  # Score multipliers
  multipliers:
    title_keyword: 2.0        # Keywords in title worth double
    multiple_keywords: 1.5    # 3+ security keywords
    action_verb_proximity: 1.3  # Action verb near security keyword

# Negative scoring signals
negative_signals:
  # Commerce and retail terms
  strong_commerce:  # Score: -40
    - "prime day"
    - "black friday"
    - "cyber monday"
    - "flash sale"
    - "limited time offer"
    - "clearance"
    
  medium_commerce:  # Score: -25
    - "deal"
    - "discount"
    - "sale"
    - "offer"
    - "promo"
    - "coupon"
    - "% off"
    - "percent off"
    
  weak_commerce:  # Score: -10
    - "price"
    - "cost"
    - "buy"
    - "shop"
    - "purchase"
    - "order"
    
  # Consumer product categories
  strong_consumer:  # Score: -30
    - "robot vacuum"
    - "vacuum cleaner"
    - "kitchen appliance"
    - "home appliance"
    - "smart home device"
    - "gaming console"
    - "headphones"
    - "earbuds"
    - "roomba"
    - "air fryer"
    - "instant pot"
    - "sous vide"
    - "coffee maker"
    - "blender"
    
  medium_consumer:  # Score: -20
    - "vacuum"
    - "kitchen"
    - "appliance"
    - "gadget"
    - "device"
    - "smart speaker"
    - "smart tv"
    - "laptop"
    - "smartphone"
    - "tablet"
    - "wearable"
    - "fitness tracker"
    - "smart watch"
    - "echo"
    - "alexa"
    - "google home"
    
  # Review and buying guide terms
  review_terms:  # Score: -35
    - "buying guide"
    - "top 10"
    - "best of"
    - "product review"
    - "unboxing"
    - "hands on"
    - "first impressions"
    - "versus"
    - "comparison"
    - "roundup"
    - "recommendations"
    
  # Security-sounding consumer products (needs special handling)
  misleading_security_terms:  # Score: -25
    - "security camera"
    - "security system" 
    - "home security"
    - "security features"
    - "security device"
    - "smart lock"
    - "doorbell camera"
    - "surveillance camera"
    
# Multipliers for negative signals in title
negative_multipliers:
  title_penalty: 1.5  # Negative signals in title get 1.5x penalty
  
# Exclusion patterns - if these are present WITHOUT security keywords, exclude
exclusion_patterns:
  # Network operations (non-security)
  - pattern: "hardware question"
    unless_contains: ["vulnerability", "exploit", "security"]
  
  - pattern: "bgp"
    unless_contains: ["hijack", "attack", "security", "vulnerability"]
  
  - pattern: "peering"
    unless_contains: ["attack", "security", "breach"]
  
  - pattern: "transit"
    unless_contains: ["attack", "security", "breach"]
  
  - pattern: "ix "
    unless_contains: ["attack", "security", "breach"]
  
  - pattern: "internet exchange"
    unless_contains: ["attack", "security", "breach"]
  
  - pattern: "asn"
    unless_contains: ["hijack", "attack", "security"]
  
  - pattern: "route"
    unless_contains: ["hijack", "attack", "security", "poisoning"]
  
  - pattern: "failover"
    unless_contains: ["attack", "security", "vulnerability"]
  
  - pattern: "load balancer"
    unless_contains: ["vulnerability", "exploit", "security"]
  
  - pattern: "bandwidth"
    unless_contains: ["ddos", "attack", "security"]
  
  # Product announcements (non-security)
  - pattern: "new feature"
    unless_contains: ["security", "vulnerability", "protection"]
  
  - pattern: "product launch"
    unless_contains: ["security", "protection", "defense"]
  
  - pattern: "now available"
    unless_contains: ["security update", "patch", "fix"]
  
  - pattern: "announces"
    unless_contains: ["breach", "vulnerability", "attack", "security"]
  
  # General tech discussions
  - pattern: "ai features"
    unless_contains: ["security", "attack", "vulnerability", "malicious"]
  
  - pattern: "chromebook"
    unless_contains: ["vulnerability", "exploit", "security", "malware"]
  
  - pattern: "laptop"
    unless_contains: ["stolen", "breach", "malware", "security"]
  
  # Business/Financial (non-security)
  - pattern: "funding"
    unless_contains: ["cybersecurity", "security", "breach"]
  
  - pattern: "acquisition"
    unless_contains: ["security", "breach", "attack"]
  
  - pattern: "ipo"
    unless_contains: ["security", "breach", "attack"]
  
  - pattern: "earnings"
    unless_contains: ["breach", "attack", "ransomware"]

# Domain-specific exclusions
excluded_domains:
  - "reddit.com"
  - "twitter.com"
  - "x.com"
  - "facebook.com"
  - "linkedin.com"
  - "youtube.com"
  - "instagram.com"
  - "tiktok.com"

# Title patterns that indicate non-security content
non_security_title_patterns:
  - "^re: .*question$"  # Reply to questions
  - "^re: hardware"     # Hardware discussions
  - "^re: network"      # Network discussions (unless security related)
  - "^re: bgp"          # BGP discussions
  - "^re: dns"          # DNS discussions (unless security related)
  - "^job posting"      # Job postings
  - "^hiring"           # Hiring posts
  - "^\\[ot\\]"        # Off-topic posts
  - "^\\[off.?topic\\]" # Off-topic posts
  - "webinar"           # Webinars
  - "live webinar"      # Live webinars
  - "upcoming webinar"  # Upcoming webinars
  - "join.*webinar"     # Join webinar invitations
  - "register.*webinar" # Webinar registrations
  - "^enisa:"           # ENISA announcements
  - "^enisa launches"   # ENISA launches
  - "^enisa publishes"  # ENISA publishes